const CONFIG = {
  SCREEN_WIDTH : 1280,
  SCREEN_HEIGHT : 720,

  ROOM_TYPE_X : 500,
  ROOM_TYPE_Y : 582,

  INSIDE_X: 717,
  INSIDE_Y: 530,

  CHARACTER_INITIAL_X: -70,
  CHARACTER_INITIAL_Y: 700,
  CHARACTER_SPEED: 3,

  ANIM: {
    IDLE_DURATION: 1500,
    DAILY_CHECK: {
      WEATHER: 270,
      ENV: 950,
      ROOM: 500,
      INSIDE: 750,
      HOUSE: 630,
      SLEEP_ROOM: 810
    },
    DAILY_ORDER: [ 'WEATHER', 'ROOM', 'INSIDE', 'ENV', 'HOUSE', 'SLEEP_ROOM' ]
  }
}

export default CONFIG;